name: noteapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
# And in deps
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  fast_log: ^1.0.7
  dart_mappable: ^4.2.2
  dialoger: ^1.0.0
  hexcolor: ^3.0.1
  shadcn_ui: ^0.6.4
  salomon_bottom_bar: ^3.3.2
  pylon: ^1.0.3+5
  toxic: ^1.3.1
  toxic_flutter: ^1.0.2+1
  fire_crud_flutter: ^1.0.1+1
  fire_crud: ^2.1.13

  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  fire_api: ^1.1.9+4
  fire_api_flutter: ^1.1.6+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
flutter:
  uses-material-design: true
scripts:
  update_json_models_force: flutter pub run build_runner build --delete-conflicting-outputs
